language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - virtualenv venv
  - source venv/bin/activate
install:
  - pip install -r requirements.txt

script:
  - pytest
